---
- hosts: all
  vars:
    db_name: wp
    db_user: root
    db_password: root
    web_root: /var/www/html/vagrant/
  tasks:
    - name: Update Box
      sudo: yes
      apt: update_cache=yes

    - name: Install Packages
      sudo: yes
      apt: pkg={{item}} state=installed
      with_items:
        - python-mysqldb
        - mysql-server
        - libapache2-mod-auth-mysql
        - apache2
        - php5
        - php5-mcrypt
        - php5-mysql
        - php5-xdebug
        - php5-curl
        - libapache2-mod-php5

    - name: php5enmod
      command: php5enmod mcrypt
      sudo: yes
      notify: restart apache2

    - name: Configuring Apache
      apache2_module: state=present name=rewrite
      sudo: yes
      notify: restart apache2

    - copy: src=files/templates/20-xdebug.ini
            dest=/etc/php5/apache2/conf.d/20-xdebug.ini
            owner=root group=root mode=0644
      sudo: yes
      notify: restart apache2

    - copy: src=files/.env
          dest={{web_root}}
          owner=www-data group=www-data mode=0644
      sudo: yes

    - copy: src=files/.htaccess
          dest={{web_root}}
          owner=www-data group=www-data mode=0644
      sudo: yes

    - copy: src=files/templates/000-default.conf
            dest=/etc/apache2/sites-available/000-default.conf
            owner=root group=root mode=0644
      sudo: yes
      notify: restart apache2

    # MySQL Config
    - name: Config MySQL User
      mysql_user: name=root password=root priv=*.*:ALL state=present

    - name: Create Table
      mysql_db: name={{db_name}} state=present login_user={{db_user}} login_password={{db_password}}

    - name: Copy SQL import
      copy: src=files/import.sql.gz dest=/tmp

    - name: Import initial SQL
      mysql_db: name={{db_name}} state=import target=/tmp/import.sql.gz login_user={{db_user}} login_password={{db_password}}

  handlers:
    - name: restart apache2
      command: service apache2 restart
      sudo: yes