#!/usr/bin/env node

var fs = require('fs'),
    hogan = require('hogan.js'),
    exec = require('child_process').exec,
    inquirer = require("inquirer"),
    parseArgs = require('minimist'),
    cliPath = __dirname+'/framework/core/vendor/cli';